services:
  - type: web
    name: powder
    env: node
    buildCommand: |
      # Install Node.js dependencies
      npm install

      # Install Python and required system packages
      apt-get update
      apt-get install -y python3 python3-pip python3-venv python3-full

      # Create and activate a virtual environment
      python3 -m venv /opt/venv
      . /opt/venv/bin/activate

      # Upgrade pip in the virtual environment
      pip3 install --upgrade pip

      # Install Python packages in the virtual environment
      pip3 install --no-cache-dir pandas==2.1.0
      pip3 install --no-cache-dir openmeteo-requests>=1.1.0
      pip3 install --no-cache-dir requests-cache>=1.1.0
      pip3 install --no-cache-dir retry-requests>=2.0.0
      pip3 install --no-cache-dir -r requirements.txt

      # Make Python scripts executable
      chmod +x getForecastFull_all_resorts.py
      chmod +x calculateAllHistory.py
      chmod +x calculateHistory.py

      # Debug information
      echo "Installed Python packages:"
      pip3 list
      echo "Python version:"
      python3 --version
    startCommand: |
      . /opt/venv/bin/activate && node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: VIRTUAL_ENV
        value: /opt/venv
      - key: PATH
        value: /opt/venv/bin:${PATH}