services:
  - type: web
    name: powder
    env: node
    buildCommand: |
      # Install Node.js dependencies
      npm install

      # Install Python and pip directly
      apt-get update
      apt-get install -y python3 python3-pip

      # Install Python packages globally (without virtual env)
      pip3 install --no-cache-dir pandas==2.1.0
      pip3 install --no-cache-dir -r requirements.txt

      # Make Python scripts executable
      chmod +x getForecastFull_all_resorts.py
      chmod +x calculateAllHistory.py
      chmod +x calculateHistory.py

      # Debug information
      echo "Installed Python packages:"
      pip3 list
      echo "Python version:"
      python3 --version
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"